wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [35, 35, 35, 35]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [10, 10, 10, 10, 10]
  refreshInterval: 1
  openFileUtil: "open"
  term: "xterm-256color"
  mods:
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    time:
      title: "Time"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Vancouver: "America/Vancouver"
        "New York": "America/New_York"
        Amsterdam: "Europe/Amsterdam"
        Moscow: "Europe/Moscow"
        Tyumen: "Asia/Yekaterinburg"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "chronological"
    prettyweather:
      enabled: true
      city: "Amsterdam"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 300
      unit: "m"
      view: 0
      language: "en"
    battery:
      type: power
      title: "⚡️"
      enabled: true
      position:
        top: 1
        left: 3
        height: 1
        width: 1
      refreshInterval: 15
    todolist:
      type: todo
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 1
        left: 0
        height: 3
        width: 1
      refreshInterval: 3600
    ip:
      type: ipinfo
      title: "My IP"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 2
      refreshInterval: 150
    security_info:
      type: security
      title: "Staying safe"
      enabled: true
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      refreshInterval: 3600
    gitlab:
      apiKey: "p0d13*********************************************c3"
      enabled: false
      position:
        top: 4
        left: 0
        height: 1
        width: 4
      refreshInterval: 300
      projects:
        - "gitlab-org/release/tasks"
        - "gitlab-org/gitlab-ce"
      username: "wtfutil"
    docker:
      type: docker
      enabled: true
      labelColor: lightblue
      focusable: true
      position:
        top: 1
        left: 1
        height: 3
        width: 1
      refreshInterval: 1
    uptime:
      type: cmdrunner
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 3
        left: 2
        height: 1
        width: 2
      refreshInterval: 30
    spotify:
      enabled: true
      colors:
        label: "green"
        text: "white"
      position:
        top: 0
        left: 2
        height: 1
        width: 2
      refreshInterval: 0
